# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0ce710fcfac182397230dfcb64996f5f"
name = "my-app"
handle = "my-app-1693"
application_url = "https://sawfish-exact-urgently.ngrok-free.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/app/order-create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_products"

[auth]
redirect_urls = [
  "https://sawfish-exact-urgently.ngrok-free.app/auth/callback",
  "https://sawfish-exact-urgently.ngrok-free.app/auth/shopify/callback",
  "https://sawfish-exact-urgently.ngrok-free.app/api/auth/callback"
]

[pos]
embedded = false
